### ISSUE TITLE
printf_config.h not included in printf.h

### ISSUE THREAD

**Issue by mickjc750** [eyalroz/printf#36]
printf.h tests for PRINTF_ALIAS_STANDARD_FUNCTION_NAMES , but can't see it as it's defined in printf_config.h

**Comment by eyalroz** [comment]
This is intentional. `printf_config.h` is a build artifact, for setting the preprocessor defines. `printf.h` takes defines, and otherwise has its defaults. That's how mpaland's version worked, and I don't think I should change that... a three-file library is a lot more files than a two-file library...
